first5destinations = []
print("Please enter your 5 travel destinations:")
for i in range(1,6):
    destination = input(f"Destination {i}: ")
    first5destinations.append(destination)
print("Original Travel Itenerary:")
print("1.", first5destinations[0])
print("2.", first5destinations[1])
print("3.", first5destinations[2])
print("4.", first5destinations[3])
print("5.", first5destinations[4])
print("Let's update your 2nd and 5th destinations:")
newdestination1 = input("Enter a new destination for position number 2: ")
newdestination2 = input("Enter a new destination for position number 5: ")
first5destinations.pop(4)
first5destinations.pop(1)
first5destinations.insert(1, newdestination1)
first5destinations.insert(4, newdestination2)
print("Updated Travel Itenerary:")
print("1.", first5destinations[0])
print("2.", first5destinations[1])
print("3.", first5destinations[2])
print("4.", first5destinations[3])
print("5.", first5destinations[4])
